### PR TITLE
Instrument Greenwave - Step 1 - Flask & Jaeger

### PR DESCRIPTION
**Pull request by apetryla**
PVCORE-3870

### CODE REVIEW

**Comment by pacho-rh** [comment]
LGTM

**Review by pacho-rh — APPROVED** [review]
LGTM

**Comment by xpokor85** [comment]
LGTM

**Review by xpokor85 — APPROVED** [review]

**Comment by xpokor85** [comment]
Even though for GitHub there is no direct link to JIRA, I would add a number of tickets for better orientation.

**Comment by mike-kingsbury** [comment]
👍

**Pull request merged**
